### ISSUE TITLE
Missing cancellation_detail throws 500

### ISSUE THREAD

**Issue by estrattonbailey** [truework/api#3]
**Describe the bug**
An invalid field is throwing a `500` instead of our normal field validation error `400`.

**To Reproduce**
Try to cancel a non-terminal Verification without providing `cancellation_detail`.

**Expected behavior**
Return `400` and a specific error message, like our other field validations.

**Comment by lindsey-truework** [comment]
We decided `cancellation_details` should be optional since that's how it is when cancelling requests in our app. This is done in truework/truework-frontend-api#3766.
